### PR TITLE
use @eval instead of @generated

### PR DESCRIPTION
**Pull request by jw3126**

### CODE REVIEW

**Comment by oxinabox** [comment]
thats a good idea

**Review by oxinabox — APPROVED** [review]
Don't forget to bump the version number so we can tag a release

**Comment by jw3126** [comment]
Yeah it is already bumped.

**Comment by jw3126** [comment]
@JuliaRegistrator register

**Review by jw3126 — COMMENTED** [review]
@JuliaRegistrator register

**Pull request merged**
