### PR TITLE
[WIP]  steal all the tests from SHA.jl

### PR DESCRIPTION
**Pull request by oxinabox**
The tricky part is getting Nettle.jl to establish all the correct answers

### CODE REVIEW

**Comment by jw3126** [comment]
I had mainly
```julia
import Nettle

@testset "compare with Nettle" begin
    for offset ∈ [0,10^3, 10^4, 10^5]
        iter = offset:(offset+1000)
        for l ∈ iter
            s = randstring(l)
            @test Nettle.hexdigest("md5", s) == bytes2hex(md5(s))
        end
    end
end
```
for tests. Something like this makes sure, that all padding scenarios are covered.

**Comment by jw3126** [comment]
Btw, can you activate travis?

**Comment by oxinabox** [comment]
I have now added travis. Github was being  having issues lastnight and wasn't picking it up (even on a sync).
Nothing will pass until @staticfloat tags a new release of SHA.jl


The SHA.jl tests want to check `update!` works correctly when called not in isolation.
So I think wrapping `Nettle.update!` is required.

**Comment by jw3126** [comment]
Okay sure! My point was its good to cover each case of `i = length(data) % 128` for all `i in 0:127` in order to test that the padding is correct. I guess we can test all three steps initialization, `update!` and `digest!` against nettle.

**Comment by oxinabox** [comment]
Closed in preference for #3

**Pull request closed without merging**
